#!/usr/bin/env ruby
# frozen_string_literal: true

# poetry-docs style registry builder.
#
# Vendors the poetry theme fragments for the docs switcher:
#
#   - refreshes the installed slots (poetry/style-default.css,
#     poetry/style-charts.css) from the sibling gems, byte-verbatim - the
#     same bytes `bin/rails g poetry:install` would write, kept in sync so
#     a future installer re-run is a no-op; and
#   - writes app/assets/tailwind/styles/style-<name>.css for ALL NINE
#     themes (default included), each fragment nested inside a
#     .style-<name> { ... } block - the upstream shadcn mechanism at
#     1773ecfe, the shadcn@4.19.0 release (apps/v4/app/style-registry.css imports wrapped style
#     fragments into layer(base)).
#
# The docs site deviates from a normal poetry install on purpose: an
# install carries ONE unscoped theme in the slot; the docs carry all nine
# scoped, with exactly one .style-<name> class on <html> at all times
# (server-rendered style-default, pre-paint swap from localStorage).
# Poetry fragments are complete visual layers - scoping all nine means no
# unscoped layer can leak tokens into a stamped theme. Upstream's shape is
# the same: their base tailwind.css is structural-only, every visual token
# lives in a per-style layer.
#
# Idempotent. Run after bumping the gems. Do not hand-edit outputs.

ROOT = File.expand_path("..", __dir__)
UI_THEMES = File.expand_path("../poetry-ui/themes", ROOT)
CHARTS_THEMES = File.expand_path("../poetry-charts/themes", ROOT)
OUT_DIR = File.join(ROOT, "app/assets/tailwind/styles")
SLOT_UI = File.join(ROOT, "app/assets/tailwind/poetry/style-default.css")
SLOT_CHARTS = File.join(ROOT, "app/assets/tailwind/poetry/style-charts.css")
THEMES = %w[default vega nova mira rhea maia luma lyra sera].freeze

def fragment(dir, name)
  path = File.join(dir, "#{name}.css")
  abort "build_style_registry: missing fragment #{path}" unless File.exist?(path)
  css = File.read(path)
  # The wrapper depends on the fragments' bare-selector contract.
  %w[@import :root].each do |bad|
    abort "build_style_registry: #{path} breaks the bare-selector contract (#{bad})" if css.include?(bad)
  end
  css.chomp
end

require "fileutils"
FileUtils.mkdir_p(OUT_DIR)

# --- slot sync (installer parity) -------------------------------------------
File.write(SLOT_UI, fragment(UI_THEMES, "default") + "\n")
File.write(SLOT_CHARTS, fragment(CHARTS_THEMES, "default") + "\n")
puts "synced slots: poetry/style-default.css, poetry/style-charts.css (default theme bytes)"

# --- wrapped fragments --------------------------------------------------------
THEMES.each do |name|
  ui = fragment(UI_THEMES, name)
  charts = fragment(CHARTS_THEMES, name)
  out = +"/* GENERATED by script/build_style_registry.rb - do not edit.\n"
  out << "   poetry #{name} theme, scope-wrapped for the docs switcher: the ui and\n"
  out << "   charts fragments from the sibling gems, nested under .style-#{name}\n"
  out << "   (upstream 1773ecfe (shadcn@4.19.0) mechanism; MIT). Regenerate after theme changes. */\n\n"
  out << ".style-#{name} {\n#{ui}\n}\n\n"
  out << ".style-#{name} {\n#{charts}\n}\n"
  path = File.join(OUT_DIR, "style-#{name}.css")
  File.write(path, out)
  rules = ui.scan(/^\.cn-/).size + charts.scan(/^\.cn-/).size
  puts "wrote styles/style-#{name}.css (#{rules} cn rules, #{out.bytesize} bytes)"
end

puts "style registry complete: #{THEMES.size} wrapped themes"
